# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec4dfe6949f1db894dd04b5a8fa3fea3a7bc91d6dc189e16ab97302d8d98cc616d7b81c97005dc40f7c7524b6c9b13ae9fe5ed875f4ef7a87d7ca043a182e91

test:
  secret_key_base: a0a927fc4ef332834f9067041bb12f214b191d1e9f50160cda8424a49bfe81f9672a94f78c4b1bbbec04aca8c869f047550359f42d42029f21b39cea52fd11f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
